#!/bin/bash
# Produces signed, notarized release assets locally. Does not publish or create tags.
set -euo pipefail
cd "$(dirname "$0")/.."
: "${LEONARDO_VERSION:?Set the release version for the selected channel}"
: "${LEONARDO_BUILD:?Set a monotonically increasing integer build}"
: "${SPARKLE_PUBLIC_KEY:?Set the public Ed25519 key generated by Sparkle}"
: "${DEVELOPER_ID_APPLICATION:?Set the Developer ID Application signing identity}"
: "${RELEASE_NOTES_FILE:?Set the Markdown release notes file}"
[ -s "$RELEASE_NOTES_FILE" ] || { echo "Missing release notes" >&2; exit 1; }
channel="${LEONARDO_CHANNEL:-stable}"
notarize="${LEONARDO_NOTARIZE:-1}"
if [ "$notarize" != 1 ] && { [ "$notarize" != 0 ] || [ "$channel" != beta ]; }; then
  echo 'Only beta candidates can skip notarization (LEONARDO_NOTARIZE=0).' >&2; exit 1
fi
if [ "$notarize" = 1 ]; then
  : "${NOTARY_PROFILE:?Set the existing notarytool Keychain profile}"
fi
assets="$PWD/output/release-$LEONARDO_VERSION"
[ ! -e "$assets" ] || { echo 'Release assets already exist; use a fresh output directory.' >&2; exit 1; }
export LEONARDO_DISTRIBUTION=1
./scripts/build-app.sh
app="$PWD/output/LeonardoMD.app"
tools="$PWD/.build/artifacts/sparkle/Sparkle/bin"
python3 scripts/verify-update-signing-key.py "$app/Contents/Info.plist" "$tools/generate_keys" "${SPARKLE_KEY_ACCOUNT:-ed25519}"
framework="$app/Contents/Frameworks/Sparkle.framework/Versions/B"
# Re-sign nested executables with this app's Developer ID, preserving vendor entitlements.
for component in "$framework/XPCServices/Downloader.xpc" "$framework/XPCServices/Installer.xpc" "$framework/Autoupdate" "$framework/Updater.app" "$app/Contents/Frameworks/Sparkle.framework" "$app"; do
  codesign --force --options runtime --timestamp --preserve-metadata=entitlements --sign "$DEVELOPER_ID_APPLICATION" "$component"
done
codesign --verify --deep --strict "$app"
notary_archive="$PWD/output/notary.zip"
ditto -c -k --sequesterRsrc --keepParent "$app" "$notary_archive"
if [ "$notarize" = 1 ]; then
  xcrun notarytool submit "$notary_archive" --keychain-profile "$NOTARY_PROFILE" --wait
  xcrun stapler staple "$app"
  xcrun stapler validate "$app"
  spctl --assess --type execute "$app"
else
  echo 'Local beta candidate: Developer ID signed, NOT notarized; do not publish as a production release.' >&2
fi
mkdir -p "$assets"
archive="$assets/LeonardoMD-$LEONARDO_VERSION.zip"
ditto -c -k --sequesterRsrc --keepParent "$app" "$archive"
# The private EdDSA key is read by Sparkle from the login Keychain.
cp "$RELEASE_NOTES_FILE" "$assets/LeonardoMD-$LEONARDO_VERSION.md"
./scripts/generate-release-appcast.sh "$tools/generate_appcast" "$assets" "$channel" "$LEONARDO_VERSION" "${SPARKLE_KEY_ACCOUNT:-ed25519}"
python3 scripts/verify-release-appcast.py "$assets/appcast.xml" "$channel"
printf 'Prepared assets: %s\n' "$assets"
# Verify the generated archive signature with Sparkle, not just its XML shape.
python3 scripts/verify-update-archive.py "$assets/appcast.xml" "$assets" "$tools/sign_update" "${SPARKLE_KEY_ACCOUNT:-ed25519}"
