#!/bin/bash
# Produces signed, notarized release assets locally. Does not publish or create tags.
set -euo pipefail
cd "$(dirname "$0")/.."
: "${LEONARDO_VERSION:?Set the stable major.minor.patch release version}"
: "${LEONARDO_BUILD:?Set a monotonically increasing integer build}"
: "${SPARKLE_PUBLIC_KEY:?Set the public Ed25519 key generated by Sparkle}"
: "${DEVELOPER_ID_APPLICATION:?Set the Developer ID Application signing identity}"
: "${RELEASE_NOTES_FILE:?Set the Markdown release notes file}"
[ -s "$RELEASE_NOTES_FILE" ] || { echo "Missing release notes" >&2; exit 1; }
: "${NOTARY_PROFILE:?Set the existing notarytool Keychain profile}"
export LEONARDO_DISTRIBUTION=1
./scripts/build-app.sh
app="$PWD/output/LeonardoMD.app"
framework="$app/Contents/Frameworks/Sparkle.framework/Versions/B"
# Re-sign nested executables with this app's Developer ID, preserving vendor entitlements.
for component in "$framework/XPCServices/Downloader.xpc" "$framework/XPCServices/Installer.xpc" "$framework/Autoupdate" "$framework/Updater.app" "$app/Contents/Frameworks/Sparkle.framework" "$app"; do
  codesign --force --options runtime --timestamp --preserve-metadata=entitlements --sign "$DEVELOPER_ID_APPLICATION" "$component"
done
codesign --verify --deep --strict "$app"
notary_archive="$PWD/output/notary.zip"
ditto -c -k --sequesterRsrc --keepParent "$app" "$notary_archive"
xcrun notarytool submit "$notary_archive" --keychain-profile "$NOTARY_PROFILE" --wait
xcrun stapler staple "$app"
xcrun stapler validate "$app"
spctl --assess --type execute "$app"
assets="$PWD/output/release-$LEONARDO_VERSION"
[ ! -e "$assets" ] || { echo 'Release assets already exist; use a fresh output directory.' >&2; exit 1; }
mkdir -p "$assets"
archive="$assets/LeonardoMD-$LEONARDO_VERSION.zip"
ditto -c -k --sequesterRsrc --keepParent "$app" "$archive"
# The private EdDSA key is read by Sparkle from the login Keychain.
tools="$PWD/.build/artifacts/sparkle/Sparkle/bin"
cp "$RELEASE_NOTES_FILE" "$assets/LeonardoMD-$LEONARDO_VERSION.md"
"$tools/generate_appcast" --embed-release-notes --download-url-prefix "https://github.com/PinedaTec-EU/LeonardoMD/releases/download/v$LEONARDO_VERSION/" "$assets"
python3 scripts/verify-release-appcast.py "$assets/appcast.xml"
printf 'Prepared assets: %s\n' "$assets"
