{
  "applied": [
    {
      "delta": {
        "build": 4
      },
      "from_version": "0.1.56",
      "merge_sha": "49665943fe9d154988987d4204fbc1e1802fc53d",
      "pr": 42,
      "to_version": "0.1.60"
    },
    {
      "delta": {
        "build": 1
      },
      "from_version": "0.1.60",
      "merge_sha": "0f13bbd6692f6bbc10acb6c0ff94136df7ace69e",
      "pr": 50,
      "to_version": "0.1.61"
    },
    {
      "delta": {
        "build": 3
      },
      "from_version": "0.1.61",
      "merge_sha": "dbddd4b3f6e39713e1590fb5947b51e495fcab9e",
      "pr": 59,
      "to_version": "0.1.64"
    },
    {
      "delta": {
        "build": 20
      },
      "from_version": "0.1.64",
      "merge_sha": "fe9bccfbe365952dfd0a359ea38c22f612fb8391",
      "pr": 52,
      "to_version": "0.1.84"
    },
    {
      "delta": {
        "build": 1
      },
      "from_version": "0.1.84",
      "merge_sha": "e594acfa496ca560065d0c9113a40d7d1c9117ff",
      "pr": 64,
      "to_version": "0.1.85"
    },
    {
      "delta": {
        "build": 1
      },
      "from_version": "0.1.85",
      "merge_sha": "63d4741fa78b7b7c84609e504cc84464c647f1b6",
      "pr": 66,
      "to_version": "0.1.86"
    },
    {
      "delta": {
        "build": 17
      },
      "from_version": "0.1.86",
      "merge_sha": "19462dd860a2892cc7a8f022270b4ca398e83d93",
      "pr": 58,
      "to_version": "0.1.103"
    },
    {
      "delta": {
        "build": 2
      },
      "from_version": "0.1.103",
      "merge_sha": "1d4789848ad283bd93fbd01eeb0e05c0c0ea9555",
      "pr": 48,
      "to_version": "0.1.105"
    },
    {
      "delta": {
        "build": 5
      },
      "from_version": "0.1.105",
      "merge_sha": "21e0ce2a6cd2069af68123382f648e81c5468a1a",
      "pr": 54,
      "to_version": "0.1.110"
    }
  ],
  "current_version": "0.1.110",
  "initial_version": "0.1.56",
  "schema_version": 1,
  "segments": [
    "release",
    "feature",
    "build"
  ]
}
