{
  "applied": [
    {
      "delta": {
        "build": 4
      },
      "from_version": "0.1.56",
      "merge_sha": "49665943fe9d154988987d4204fbc1e1802fc53d",
      "pr": 42,
      "to_version": "0.1.60"
    },
    {
      "delta": {
        "build": 1
      },
      "from_version": "0.1.60",
      "merge_sha": "0f13bbd6692f6bbc10acb6c0ff94136df7ace69e",
      "pr": 50,
      "to_version": "0.1.61"
    },
    {
      "delta": {
        "build": 3
      },
      "from_version": "0.1.61",
      "merge_sha": "dbddd4b3f6e39713e1590fb5947b51e495fcab9e",
      "pr": 59,
      "to_version": "0.1.64"
    }
  ],
  "current_version": "0.1.64",
  "initial_version": "0.1.56",
  "schema_version": 1,
  "segments": [
    "release",
    "feature",
    "build"
  ]
}
